### ISSUE TITLE
Delete grails-profile-repository fork

### ISSUE THREAD

**Issue by graemerocher** [dpcasady/grails-jasmine-resources#4]
Hi, this is not the right place, but needed a way to reach out to you. Could you please delete your fork of https://github.com/grails/grails-profile-repository

Right now github thinks your repo is the original because we moved the repo from https://github.com/grails-profiles/grails-profile-repository to https://github.com/grails/grails-profile-repository

By deleting your fork https://github.com/grails/grails-profile-repository should become the original again.

**Comment by dpcasady** [comment]
Not a problem, it's done!

**Comment by graemerocher** [comment]
Thanks!
